name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: yarn
        working-directory: packages/ui

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: packages/ui
          buildScriptName: build-stories
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
